server:
  port: 9999
mqtt:
  host: "tcp://127.0.0.1:1883"
  #  host: "ssl://127.0.0.1:8883"
  username: "emqx"
  password: "public"
  connectionTimeout: 0 # 设置超时时间 单位为秒
  keepAliveInterval: 5 # 设置会话心跳时间 单位为秒 服务器会每隔1.5*20秒的时间向客户端发送个消息判断客户端是否在线，但这个方法并没有重连的机制
  cleanSession: true  # 设置是否清空session,这里如果设置为false表示服务器会保留客户端的连接记录，这里设置为true表示每次连接到服务器都以新的身份连接
  automaticReconnect: true # 是否自动重连


